Prevents error message "no TicketID" on sending an answer if no TicketID exists.
znuny/Znuny pull request #133
Opened 2021-09-09 14:13 UTC by reneeb

## Proposed change

- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

In some situations when an agent sends an answer the CheckSubject function is called, but the TicketID isn't passed.

- This PR is related to forum discussion: https://community.znuny.org/viewtopic.php?f=35&t=42655

## Checklist

- [X] The code change is tested and works locally.(❗)
- [X] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

(Replacement PR for #118)

2021-10-21 12:18 UTC, dennykorsukewitz requested changes

2021-10-21 12:18 UTC, dennykorsukewitz commented on var/httpd/htdocs/js/Core.Agent.TicketCompose.js
> +        var ForTicketID    = $('input[name=TicketID]').val();
```suggestion
        var TicketID    = $('input[name=TicketID]').val();
```

2021-10-21 12:18 UTC, dennykorsukewitz commented on var/httpd/htdocs/js/Core.Agent.TicketCompose.js
> +        if ( !ForTicketID ) {
```suggestion
        if ( !TicketID ) {
```

2021-10-21 12:18 UTC, dennykorsukewitz commented on var/httpd/htdocs/js/Core.Agent.TicketCompose.js
> +                TicketID: ForTicketID,
```suggestion
                TicketID: TicketID,
```

2021-11-07 15:52 UTC, reneeb commented on var/httpd/htdocs/js/Core.Agent.TicketCompose.js
> +                TicketID: ForTicketID,
Changed...

2021-11-09 08:32 UTC, dennykorsukewitz approved these changes
Thank you! :rocket:

2021-11-25 11:36 UTC, merged