Bugfix and Feature for 0050-CIC-CustomerUserList
znuny/Znuny pull request #147
Opened 2021-09-25 18:10 UTC by BuTzZ

## Proposed change

When customer users are assigned to multiple customers (AdminCustomerUserCustomer), this relationship was not resolved correctly in dashboard tool 0050-CIC-CustomerUserList. Only customers that were directly assigned via AdminCustomerUser were displayed.
In comparison, however, this worked in the 0050-CIC-CustomerIDList counterpart.

In 0050-CIC-CustomerIDList there was also a button to directly influence these relationships and I have also now included this for 0050-CIC-CustomerUserList.

- '1 - 🐞 bug 🐞' : When customer users are assigned to multiple customers (AdminCustomerUserCustomer), this relationship was not resolved correctly in dashboard tool 0050-CIC-CustomerUserList.
- '1 - 🚀 feature': In 0050-CIC-CustomerIDList there was also a button to directly relationships between customer and customerusers. Added this button for 0050-CIC-CustomerUserList.

## Additional information

## Checklist

- [X] The code change is tested and works locally.(❗)
- [X] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

2021-09-25 19:11 UTC, BuTzZ commented
@dennykorsukewitz could you explain me the codepolicy in this case?

2021-09-27 07:37 UTC, dennykorsukewitz commented
Hi @BuTzZ 

> @dennykorsukewitz could you explain me the codepolicy in this case?

Yes, i would be happy to explain.

## CodePolicy Error Message
```perl
[checked] Kernel/Output/HTML/Dashboard/CustomerUserList.pm
TidyAll::Plugin::OTRS::Perl::PerlCritic
Variable, subroutine, and package names have to be in CamelCase: $tmpMemberCustomer at line 104, column 12. (no explanation).
Variable, subroutine, and package names have to be in CamelCase: $tmpMemberCustomer at line 105, column 42. (no explanation).
            return {
                Success => 0,
                Message => $LayoutObject->{LanguageObject}
                    ->Translate( 'Parameter %s is missing in %s.', $Needed, '_RenderPendingTime' ),
            };
        }
    }

```


## Code

```perl
   MemberCustomerID:
    for my $MemberCustomerID (@MemberCustomerIDs)
    {
    	my $tmpMemberCustomer = { $CustomerUserObject->CustomerSearch( UserLogin => $MemberCustomerID ) };
	    $CustomerIDs = { %$CustomerIDs, %$tmpMemberCustomer };
    }
```

https://github.com/znuny/Znuny/pull/147/files#diff-4f1142ddd65fb676f831e9ed7edcbb9d64fefc91af55bce9735ac36ad58f6d1cR104

## Solution

In the OTRS framework it is common to write variables in CamelCase style. 
❌  `nocamlecase`
❌  `noCamelCase`
✅  `YesCamelCase` 

This is certainly a bit unusual for many developers, but we will keep this style to keep the code readable.

👍🏼

2021-09-28 09:43 UTC, BuTzZ commented
Thank you for your explanation. ;-) I have understood and adapt the code immediately.

2022-03-02 10:02 UTC, dennykorsukewitz requested changes
Hi @BuTzZ 

I have added the suggested changes.

Please create 2 pull requests next time. 
One is a fix ...the other is a feature.

best 🚀

2022-03-02 10:02 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Dashboard/CustomerUserList.pm
> +    }
```suggestion
    # if we are using multiple CustomerIDs for a CustomerUser, we have to expand our CustomerIDs variable
    my @CustomerUserIDs = $CustomerUserObject->CustomerUserCustomerMemberList(
        CustomerID => $Param{CustomerID},
    );

    CUSTOMERUSERID:
    for my $CustomerUserID (@CustomerUserIDs){
        my %CustomerUserList = $CustomerUserObject->CustomerSearch( UserLogin => $CustomerUserID );
        next CUSTOMERUSERID if !%CustomerUserList;
        $CustomerIDs = { %$CustomerIDs, %CustomerUserList };
    }
```

2022-03-02 10:02 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Templates/Standard/AgentDashboardCustomerUserList.tt
>  [% RenderBlockEnd("ContentLargeCustomerUserAdd") %]
```suggestion
[% RenderBlockStart("ContentLargeCustomerIDAdd") %]
<a class="CallForAction SpacingBottom" href="[% Env("Baselink") %]Action=AdminCustomerUserCustomer;Subaction=Customer;ID=[% Data.CustomerID | uri %]"><span><i class="fa fa-plus-square"></i> [% Translate("Change CustomerID Relations") | html %]</span></a>
[% RenderBlockEnd("ContentLargeCustomerIDAdd") %]

[% RenderBlockStart("ContentLargeCustomerUserAdd") %]
<a class="CallForAction SpacingBottom" href="[% Env("Baselink") %]Action=AdminCustomerUser;Subaction=Add;CustomerID=[% Data.CustomerID | uri %]"><span><i class="fa fa-plus-square"></i> [% Translate("Add Customer User") | html %]</span></a>
[% RenderBlockEnd("ContentLargeCustomerUserAdd") %]
```

2022-03-02 10:02 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Dashboard/CustomerUserList.pm
> +    }
```suggestion
    # show change customer relations button if the agent has permission
    my $ChangeCustomerReleationsAccess = $LayoutObject->Permission(
        Action => 'AdminCustomerUserCustomer',
        Type   => 'rw',
    );

    if ($ChangeCustomerReleationsAccess) {
        $LayoutObject->Block(
            Name => 'ContentLargeCustomerIDAdd',
            Data => {
                CustomerID => $Param{CustomerID},
            },
        );
    }
```

2022-03-02 11:07 UTC, BuTzZ commented
> Hi @BuTzZ
> 
> I have added the suggested changes.
> 
> Please create 2 pull requests next time. One is a fix ...the other is a feature.
> 
> best rocket

Sure, will do it next time :)

2022-09-02 11:05 UTC, dennykorsukewitz approved these changes

2022-09-02 11:07 UTC, merged