Sector Nord AG: Added transition action AppointmentUpdate and AppointmentDelete
znuny/Znuny pull request #196
Opened 2022-01-27 13:58 UTC by jsinagowitz

## Proposed change

Currently it is only possible to create appointments from a transition action. In consultation with Shawn Beasley we added the transition actions to update and delete an appointment.

- '1 - 🚀 feature'

## Additional information

I also updated the transition action template to help users finding the correct parameters. (ProcessManagement.xml)

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

2022-01-28 10:16 UTC, dennykorsukewitz reviewed
Hi @jsinagowitz 

I've only had a very brief look at the code, so I'll just make a few quick points before taking a closer look (after your changes).

- great that you extend the SysConfig `ProcessManagement::TransitionAction::DefaultParameters###001-Framework` 👍🏼 
- **AppointmentDelete** => **AppointmentRemove** (DynamicFieldRemove) please keep the same in the context. (I do not like 'remove' either, because the function ends with 'delete'. But we should stay consistent here.)
- I have to tell you something... I am a UnitTest fan. I know I'm annoying you contributors with this, but someone has to be the annoying one. 😈 

Thanks 🚀

2022-02-04 10:05 UTC, jsinagowitz commented
Hi @dennykorsukewitz 

I just renamed the module AppointmentDelete and added some unittests.

Please have a look 🚀

2022-02-04 11:41 UTC, dennykorsukewitz requested changes
Hi @jsinagowitz

thank you.
Please use always the CodePolicy to check you code.

https://github.com/znuny/ZnunyCodePolicy/blob/master/doc/en/feature.md#usage

## Usage
```
perl $WORKSPACE/ZnunyCodePolicy/bin/otrs.CodePolicy.pl --file Test.pm
perl $WORKSPACE/ZnunyCodePolicy/bin/otrs.CodePolicy.pl --file Kernel/System/ProcessManagement/TransitionAction/AppointmentRemove.pm
```
 
## Result
```bash
 TidyAll::Plugin::Znuny::Perl::ObjectDependencies

The following objects are not longer used in the code, but declared as dependencies:

    'Kernel::System::DateTime',


[tidied]  Kernel/System/ProcessManagement/TransitionAction/AppointmentRemove.pm
```
`Kernel::System::DateTime` is obsolete... etc.


--- 

Please have a look at my comments, start the CodePolicy and improve the code accordingly.

I will certainly notice something else in the next QA round, but I am already very satisfied for now.

All in all: good job, so far. :rocket:
Thanks

2022-02-04 11:41 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/ProcessManagement.xml
> +                <Item Key="AppointmentDelete">
```suggestion
                <Item Key="AppointmentRemove">
```

2022-02-04 11:41 UTC, dennykorsukewitz commented on Kernel/System/ProcessManagement/TransitionAction/AppointmentRemove.pm
> +use Kernel::System::VariableCheck qw(:all);
If you are not use one of the VariableCheck functions, you can delete this use.

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentRemove.t
> +use Kernel::System::VariableCheck qw(:all);
Is this needed?

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentRemove.t
> +my $ConfigObject       = $Kernel::OM->Get('Kernel::Config');
Is this needed?

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentRemove.t
> +    CalendarName => 'Calendar 1',
If the calendar already exists, you will have a problem. 
Either you update the calendar or you use RandomID in Name etc.

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentRemove.t
> +        Name       => 'appid',
Please always use very meaningful variable names. 
appid = AppointmentID

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentRemove.t
> +        AppointmentID => '<OTRS_TICKET_DynamicField_appid>',
Top! I like that very much that you're testing this. 👍🏼 👍🏼

2022-02-04 11:41 UTC, dennykorsukewitz commented on Kernel/System/ProcessManagement/TransitionAction/AppointmentUpdate.pm
> +sub _ValidDateTimeConvert {
The function has now been defined twice.
In 
**Kernel::System::ProcessManagement::TransitionAction::AppointmentCreate**
and 
**Kernel::System::ProcessManagement::TransitionAction::AppointmentUpdate.**

So this should now be moved to **Kernel::System::ProcessManagement::TransitionAction::Base;**.

2022-02-04 11:41 UTC, dennykorsukewitz commented on scripts/test/ProcessManagement/TransitionAction/AppointmentUpdate.t
> +my $ConfigObject       = $Kernel::OM->Get('Kernel::Config');
Is this needed?
Please also note the same comments as in the UnitTest AppointmentRemove.t here

2022-02-04 15:06 UTC, jross93 commented
Hi @dennykorsukewitz 

I added all improvements to the code. I shouldn't have trusted the AppointmentCreate.t. 😄 
I used it for the base. So I just updated the changes to this unit test too!

Wishing you a nice weekend 🚀

2022-02-16 09:07 UTC, dennykorsukewitz approved these changes

2022-02-16 09:11 UTC, merged