Sector Nord AG: Calendar appointment plugin AppointmentID data type fix
znuny/Znuny pull request #308
Opened 2022-10-18 09:10 UTC by LuBroering

## Proposed change
Change of the data type for the appointment_id in the table calendar_appointment_plugin. 

## Type of change
- '1 - 💎 code quality'      - Code quality improvements to existing code or addition of unit tests

## Breaking change

## Additional information
We had an issue with the small int on productive systems. 

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

2023-01-12 07:53 UTC, jepf commented
@LuBroering 

Thank you for the pull request and sorry for the delay.
May I kindly ask you to resolve the merge conflict that popped up in the meantime? I will merge it then.

Please be aware that dev branch now is the upcoming 6.5.1 and currently does not contain any db upgrade migrations. 
So you would have to also add the module to the task list in scripts/Migration/Znuny/UpgradeDatabaseStructure.pm.

Thank you.

2023-01-12 07:53 UTC, jepf approved these changes

2023-03-29 08:55 UTC, dennykorsukewitz commented
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

2023-06-09 11:57 UTC, dennykorsukewitz commented
Hi @LuBroering 

This branch has conflicts that must be resolved.

Thank you! 🚀

2023-06-29 08:17 UTC, LuBroering commented
Hi @dennykorsukewitz,

the conflicts are resolved.

2023-07-04 12:42 UTC, dennykorsukewitz requested changes

2023-07-04 12:42 UTC, dennykorsukewitz commented on scripts/Migration/Znuny/UpgradeDatabaseStructure/CalendarAppointmentID.pm
> +# Copyright (C) 2021-2022 Znuny GmbH, https://znuny.org/
```suggestion
# Copyright (C) 2021 Znuny GmbH, https://znuny.org/
```

2023-07-04 12:42 UTC, dennykorsukewitz commented on scripts/Migration/Znuny/UpgradeDatabaseStructure/CalendarAppointmentID.pm
> +=head1 SYNOPSIS
```suggestion
);

=head1 SYNOPSIS
```

2023-07-04 12:42 UTC, dennykorsukewitz commented on scripts/Migration/Znuny/UpgradeDatabaseStructure/CalendarAppointmentID.pm
> +    );
```suggestion
        </TableAlter>'
    );
```

2023-07-04 13:19 UTC, dennykorsukewitz approved these changes

2023-07-04 13:31 UTC, merged