Fixed reloading of the toolbar modules
znuny/Znuny pull request #317
Opened 2022-11-11 00:14 UTC by tipue-dev

## Proposed change

If the reload for pages is activated by an agent, a page- and a toolbar-reload will be active.
![image](https://user-images.githubusercontent.com/80031303/201231526-514be802-e39a-4732-b583-151ef88623a1.png)
With this feature enabled, we get the following problems:

- The toolbar is needlessly reloaded on pages that are fully reloaded in the same time span.
- The current code identifies the toolbar modules by their classes, which doesn't work for CustomerUser search and the Customer search, and results in them being replaced by full-text search fields instead.
- The search profile drop-down isn't modernized after the refresh

I also think to create a full header and cutting it down with RegEx isn't a very elegant solution.

https://user-images.githubusercontent.com/80031303/201231334-2a82c4af-ec1c-484e-86ae-a0f91e1ccd02.mp4

1 - 🐞 bug 🐞

## Breaking change

## Additional information

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [x] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

2022-11-11 08:53 UTC, tipue-dev commented
The tests that failed for two of my commits are different and one of those ran without problems on my fork on GitHub and locally, so i **assume** it is not because of my code, but the tests just don't run perfectly yet.

2023-01-20 08:47 UTC, dennykorsukewitz requested changes
Hi  @tipue-dev ,
thanks for your PR.

I have a few change requests here.
But all in all, wonderful again. :+1: :rocket:

This fixes the errors that occurred: https://github.com/znuny/Znuny/commit/3eec62be923b35af8a89e86a5bf3060846010f2d

Regards :rocket:

2023-01-20 08:47 UTC, dennykorsukewitz commented on Kernel/Modules/AgentDashboardCommon.pm
> +        if ( ref $ToolBarModule eq 'HASH' ) {
```suggestion
        if ( IsHashRefWithData($ToolBarModule) ) {
```

2023-01-20 08:47 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Layout.pm
> +    my $MainObject = $Kernel::OM->Get('Kernel::System::Main');
```suggestion
    my $MainObject   = $Kernel::OM->Get('Kernel::System::Main');
```

2023-01-20 08:47 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Layout.pm
> +    my %Jobs = %{$Param{ToolBarModule}};
```suggestion
    my %Jobs = %{ $Param{ToolBarModule} };
```

2023-01-20 08:47 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Templates/Standard/HeaderToolbar.tt
> +# Copyright (C) 2021-2022 Znuny GmbH, https://znuny.org/
```suggestion
# Copyright (C) 2021 Znuny GmbH, https://znuny.org/
```

2023-01-20 08:49 UTC, dennykorsukewitz approved these changes

2023-01-20 10:40 UTC, merged