Sort values in AdminDynamicFieldScreenConfiguration
znuny/Znuny pull request #327
Opened 2022-12-22 20:56 UTC by eyazi

## Proposed change

In „Assignment of dynamic fields to screens“ (AdminDynamicFieldScreenConfiguration) screens and default columns get sorted by the key of the setting and not the value of the setting.

This PR adds proper sorting. The „sorting“ doesn't look that bad on the screenshots below, but if you add your own screens where the key differs from the screen name, the view gets confusing very fast.

## Type of change
- '1 - 🚀 feature'

## Additional information

Old:
<img width="400" alt="Old" src="https://user-images.githubusercontent.com/5484272/209222544-abccab78-4dfa-4af8-a6f5-4c4e31edc1e6.png">

New:
<img width="400" alt="New" src="https://user-images.githubusercontent.com/5484272/209222564-93423c97-6b0d-4387-8f50-36d0fbd6fb3a.png">

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [] Local UnitTests / Selenium passed.(❕)
- [] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

2023-01-10 09:03 UTC, dennykorsukewitz commented
Hi  @eyazi ,
thanks for your PR.

Please, keep your fork up-to-date with the upstream repository. 
[Syncing a fork 🚀  🆙 ](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

Regards :rocket:

2023-01-10 14:14 UTC, NiklasSchmitt commented
Hi @eyazi,

thank you for your PR. I would like to accept and merge it but first you have to cleanup the code that the ZnunyCodePolicy and all other pipelines successes. Also, please [sync your fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) with the upstream repository.

Best regards,
Niklas Schmitt :coffee: :rocket:

2023-01-23 07:47 UTC, dennykorsukewitz requested changes
```diff --git a/Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm b/Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
index 0767c2f927..a292d6b14f 100644
--- a/Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
+++ b/Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
@@ -278,7 +278,9 @@ sub _ShowOverview {

     $LayoutObject->Block( Name => 'Overview' );

-    for my $DynamicFieldScreen ( sort { $DynamicFieldScreens{$a} cmp $DynamicFieldScreens{$b} } keys %DynamicFieldScreens ) {
+    for my $DynamicFieldScreen ( sort { $DynamicFieldScreens{$a} cmp $DynamicFieldScreens{$b} }
+        keys %DynamicFieldScreens )
+    {
         $LayoutObject->Block(
             Name => 'DynamicFieldScreenOverviewRow',
             Data => {
@@ -288,7 +290,9 @@ sub _ShowOverview {
         );
     }

-    for my $DefaultColumnsScreen ( sort { $DefaultColumnsScreens{$a} cmp $DefaultColumnsScreens{$b} } keys %DefaultColumnsScreens ) {
+    for my $DefaultColumnsScreen ( sort { $DefaultColumnsScreens{$a} cmp $DefaultColumnsScreens{$b} }
+        keys %DefaultColumnsScreens )
+    {
         $LayoutObject->Block(
             Name => 'DefaultColumnsScreenOverviewRow',
             Data => {
(END)
```

2023-01-23 07:47 UTC, dennykorsukewitz commented on Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
> +    for my $DynamicFieldScreen ( sort { $DynamicFieldScreens{$a} cmp $DynamicFieldScreens{$b} } keys %DynamicFieldScreens ) {
```suggestion
    for my $DynamicFieldScreen ( sort { $DynamicFieldScreens{$a} cmp $DynamicFieldScreens{$b} }
        keys %DynamicFieldScreens )
    {
```

2023-01-23 07:47 UTC, dennykorsukewitz commented on Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
> +    for my $DefaultColumnsScreen ( sort { $DefaultColumnsScreens{$a} cmp $DefaultColumnsScreens{$b} } keys %DefaultColumnsScreens ) {
```suggestion
    for my $DefaultColumnsScreen ( sort { $DefaultColumnsScreens{$a} cmp $DefaultColumnsScreens{$b} }
        keys %DefaultColumnsScreens )
    {
```

2023-01-23 10:48 UTC, dennykorsukewitz reviewed
@eyazi sorry for that.

Today the code policy is bit ...

2023-01-23 10:48 UTC, dennykorsukewitz commented on Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
> +    {
```suggestion
    for my $DynamicFieldScreen (
        sort { $DynamicFieldScreens{$a} cmp $DynamicFieldScreens{$b} }
        keys %DynamicFieldScreens
        )
    {
```

2023-01-23 10:48 UTC, dennykorsukewitz commented on Kernel/Modules/AdminDynamicFieldScreenConfiguration.pm
> +    {
```suggestion
    for my $DefaultColumnsScreen (
        sort { $DefaultColumnsScreens{$a} cmp $DefaultColumnsScreens{$b} }
        keys %DefaultColumnsScreens
        )
    {
```

2023-01-23 13:07 UTC, dennykorsukewitz approved these changes

2023-01-23 14:50 UTC, NiklasSchmitt approved these changes

2023-01-23 18:20 UTC, merged