Fixed SearchInArchive parameter not used in the fulltext search of the toolbar.
znuny/Znuny pull request #479
Opened 2023-08-16 20:06 UTC by tipue-dev

## Proposed change

SearchInArchive search parameter isn't used in the toolbar search anymore, because the block 'ToolBarSearchFulltext' has been removed and the condition to check if the parameter should be added didn't get any Data anymore.

Additionally, the test (Selenium/Output/ToolBar/TicketSearchFulltext.t) failed because of this, and because the search menu had to be opened to select fulltext-search.

1 - 🐞 bug 🐞

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [x] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

2023-09-26 14:20 UTC, dennykorsukewitz requested changes

2023-09-26 14:20 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Layout.pm
>          }
```suggestion
        if (
            $ConfigObject->Get('Ticket::ArchiveSystem')
            && $Modules{$Key}->{Block} eq 'ToolBarSearch'
            && $Modules{$Key}->{Name} eq 'Fulltext'
        ){
            my $SearchInArchive = $ConfigObject->Get('Ticket::Frontend::AgentTicketSearch')->{Defaults}->{SearchInArchive};

            $Self->Block(
                Name => 'SearchInArchive',
                Data => {
                    SearchInArchive => $SearchInArchive || 'AllTickets',
                },
            );
        }
```

2023-11-06 12:59 UTC, NiklasSchmitt commented on Kernel/Output/HTML/Layout.pm
>          }
code policy failed. Here is my suggestion with the fixed lines by code policy.

```suggestion
        if (
            $ConfigObject->Get('Ticket::ArchiveSystem')
            && $Modules{$Key}->{Block} eq 'ToolBarSearch'
            && $Modules{$Key}->{Name} eq 'Fulltext'
            )
        {
            my $SearchInArchive
                = $ConfigObject->Get('Ticket::Frontend::AgentTicketSearch')->{Defaults}->{SearchInArchive};

            $Self->Block(
                Name => 'SearchInArchive',
                Data => {
                    SearchInArchive => $SearchInArchive || 'AllTickets',
                },
            );
        }
```

2023-11-06 13:01 UTC, NiklasSchmitt approved these changes

2023-12-01 08:17 UTC, merged