Tasks that communicate with external services disabled by default
znuny/Znuny pull request #50
Opened 2021-04-09 11:44 UTC by pboguslawski

Tasks that communicate with external services disabled by default.

Related: 42374d0
Author-Change-Id: IB#1046362

2021-05-25 07:58 UTC, rkaldung commented
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

2021-05-28 08:19 UTC, pboguslawski commented
Done.

2021-06-15 12:40 UTC, dennykorsukewitz commented
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

2021-06-15 13:34 UTC, pboguslawski commented
Done.

2021-08-20 07:52 UTC, dennykorsukewitz requested changes

2021-08-20 07:52 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/Daemon.xml
> +    <Setting Name="Daemon::SchedulerCronTaskManager::Task###SupportDataCollectAsynchronous" Required="0" Valid="0" ConfigLevel="100">
```suggestion
    <Setting Name="Daemon::SchedulerCronTaskManager::Task###SupportDataCollectAsynchronous" Required="1" Valid="1" ConfigLevel="100">
```

We will not disable this SysConfig by default.
However, we will remove `ReadOnly`.

2021-08-20 07:52 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/Framework.xml
> -                </Item>
Can you please undo the change.
The change does not fit thematically with the others (subject). 
Keep it simple. You are welcome to use another pull request.

2021-08-20 07:52 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Templates/Standard/AgentPreferences.tt
> -                                [% END %]
Can you please undo the change.
The change does not fit thematically with the others (subject). 
Keep it simple. You are welcome to use another pull request.

2021-08-20 07:53 UTC, dennykorsukewitz commented
@pboguslawski 

Please solve the conflicting files:
`Kernel/Config/Files/XML/CloudServices.xml`

2021-08-27 08:23 UTC, pboguslawski commented on Kernel/Config/Files/XML/Daemon.xml
> +    <Setting Name="Daemon::SchedulerCronTaskManager::Task###SupportDataCollectAsynchronous" Required="0" Valid="0" ConfigLevel="100">
This task should be enabled only if admin expicity wants it (it wastes resources). We won't remove it. Feel free to adapt to your needs.

2021-08-27 08:24 UTC, pboguslawski commented on Kernel/Config/Files/XML/Framework.xml
> -                </Item>
Subject changed. This ad should be removed and wont be removed from this PR. Feel free to adapt to your needs.

2021-08-27 08:24 UTC, pboguslawski commented on Kernel/Output/HTML/Templates/Standard/AgentPreferences.tt
> -                                [% END %]
Subject changed. This ad should be removed and wont be removed from this PR. Feel free to adapt to your needs.

2021-08-27 08:28 UTC, pboguslawski commented
Conflict in CloudServices.xml resolved.

2021-08-31 07:54 UTC, dennykorsukewitz commented
Hi @pboguslawski

I think you have misunderstood me.
If your PR requires multiple labels / descriptions to be applied, you'll most likely need to split it into multiple PRs. 
This makes things easier and faster for the code review. In the future we can better find and understand the changes.

**We will not merge pull requests whose code change includes multiple topics!
Changing the title is not a solution, it is not acceptable!** 👎🏼 


I'm sorry, but if you don't give us a better reason for your code changes and we don't want to adopt the code, then the code stays as it is. 

We are always open and happy to discuss the changes. 👍🏼 


`Feel free to adapt to your needs.` - Paweł We have to think about all users of this system.

2021-08-31 07:56 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Templates/Standard/AgentPreferences.tt
> -                                [% END %]
**We will not merge pull requests whose code change includes multiple topics!
Changing the title is not a solution, it is not acceptable! **
Please create a new pull request for this.

2021-08-31 07:56 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/Framework.xml
> -                </Item>
**We will not merge pull requests whose code change includes multiple topics!
Changing the title is not a solution, it is not acceptable! **
Please create a new pull request for this.

2021-08-31 07:58 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/Daemon.xml
> +    <Setting Name="Daemon::SchedulerCronTaskManager::Task###SupportDataCollectAsynchronous" Required="0" Valid="0" ConfigLevel="100">
If 'ReadOnly' is removed you can adapt to your needs.
If you have no more reason - We will not disable this SysConfig by default.

2021-08-31 08:03 UTC, pboguslawski commented
> We will not merge pull requests whose code change includes multiple topics!
> Changing the title is not a solution, it is not acceptable!

Previous upstream stuff cleanup is maintained by us in one branch. Feel free to close this PR it you don't like it and use it or use it as base for your own cleanups.

2021-08-31 10:36 UTC, dennykorsukewitz commented
The PullRequest is almost OK.
1. Two topics in one PullRequest are not clear enough.
   Please simply create another one and everything will be fine.

2. Simply make the change and then we can merge.

2021-08-31 10:53 UTC, pboguslawski commented
> Two topics in one PullRequest are not clear enough

This PR turns off (when parameter is available in sysconfig) or removes from code (when function is hardcoded without parameter in sysconfig) previous upstream integration stuff. It is ONE topic. Separating removal of hardcode to different PR costs time - feel free to do it yourself if you still see its sensible (we don't).

2021-12-06 14:39 UTC, dennykorsukewitz commented
Since our PullRequest rules were not followed and a discussion with the contributor did not bring any further success, we close this PullRequest and solve the problem with the following commit.

https://github.com/znuny/Znuny/commit/d4913719767c08d280d5e8ea4fd6f6ab6c442a26

2021-12-06 14:39 UTC, closed without merging