Configurable MaxNumberOfOptions #575
znuny/Znuny pull request #576
Opened 2024-06-27 11:11 UTC by itweserems

## Proposed change
See #575:
When using dynamic fields of type "dropdown" or "multiselect", the default code-setup is that the layout of a select-field (e.g. dynamic field) will be changed when the amount of selectable values is above 1000.

This is for performance reasons, but the limit should be configurable. The layout for fields with >1000 values does not allow searching values and with a configurable maximum number can be set to an individual level to keep the search functionality as long as performance goes along with this.

## Type of change
1 - 🚀 feature

## Breaking change

## Additional information

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

2024-06-27 15:58 UTC, rkaldung commented
@jepf Please check the new system configuration name, the feature looks fine.

2024-10-30 10:25 UTC, dennykorsukewitz requested changes
Hi  @itweserems ,
thanks for your PR.

I have a few change requests here.

Regards :rocket:

2024-10-30 10:25 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Layout.pm
> +
```suggestion
    # For performance reasons:
    # Do not initialize modernized input fields on selections with many entries
    my $MaxNumberOfOptions = $Kernel::OM->Get('Kernel::Config')->Get("InputFields::ModernizedSelection::MaxNumberOfOptions");
    $Self->AddJSData(
        Key   => 'InputFields::ModernizedSelection::MaxNumberOfOptions',
        Value => $MaxNumberOfOptions,
    );

```

2024-10-30 10:25 UTC, dennykorsukewitz commented on Kernel/Language/de.pm
> +            'Legt die maximale Anzahl an Werten fest, bevor das Auswahlfeld-Layout zu Performancezwecken geändert wird.',
```suggestion
        'Limits the number of options for modernized selection fields. If this limit will be exceeded, the selection field will for performance reasons be shown as non-modernized.' =>
            'Limitiert die Anzahl an Optionen für modernized Auswahlfelder. Wenn das Limit überschritten ist, wird das Auswahlfeld aus Performancegründen als nicht-modernized angezeigt.',
```

2024-10-30 10:25 UTC, dennykorsukewitz commented on Kernel/Config/Files/XML/Framework.xml
> +    </Setting>
```suggestion
    <Setting Name="InputFields::ModernizedSelection::MaxNumberOfOptions" Required="1" Valid="1">
        <Description Translatable="1">Limits the number of options for modernized selection fields. If this limit will be exceeded, the selection field will for performance reasons be shown as non-modernized.</Description>
        <Navigation>Frontend::Base</Navigation>
        <Value>
            <Item ValueType="String" ValueRegex="^\d+$">1000</Item>
        </Value>
    </Setting>
```

Please move this setting after:

```
    <Setting Name="ModernizeCustomerFormFields" Required="1" Valid="1">
        <Description Translatable="1">Use new type of select and autocomplete fields in customer interface, where applicable (InputFields).</Description>
        <Navigation>Frontend::Customer</Navigation>
        <Value>
            <Item ValueType="Checkbox">1</Item>
        </Value>
    </Setting>
```

2024-10-30 10:25 UTC, dennykorsukewitz commented on var/httpd/htdocs/js/Core.UI.InputFields.js
> +            if ($(SelectObj).children('option').length > MaxDropdownOptions) {
```suggestion
            MaxNumberOfOptions = Core.Config.Get('InputFields::ModernizedSelection::MaxNumberOfOptions');
            if ($(SelectObj).children('option').length > MaxNumberOfOptions) {
```

2024-10-30 10:27 UTC, dennykorsukewitz commented
Hi @itweserems 

Please move this setting after:

```
    <Setting Name="ModernizeCustomerFormFields" Required="1" Valid="1">
        <Description Translatable="1">Use new type of select and autocomplete fields in customer interface, where applicable (InputFields).</Description>
        <Navigation>Frontend::Customer</Navigation>
        <Value>
            <Item ValueType="Checkbox">1</Item>
        </Value>
    </Setting>
```

2024-10-31 21:52 UTC, dennykorsukewitz approved these changes

2024-11-01 11:52 UTC, merged

2024-12-13 19:27 UTC, itweserems commented
Hi @dennykorsukewitz,
sorry for not responding on this but thanks for making the changes and merging this!

BR 🚀

2024-12-13 19:30 UTC, dennykorsukewitz commented
> Hi @dennykorsukewitz, sorry for not responding on this but thanks for making the changes and merging this!
> 
> BR, Paul 🚀

Hi @itweserems 

I usually have more patience and wait, but I didn't want to leave this finished PullRequest lying around unnecessarily. 
Thanks for your contribution.

👍🏼 🚀