1 - bug Fixed error "Can't sign: unable to write 'random state'" if sending emails signed with S/MIME. – OTRS bug #14522
znuny/Znuny pull request #72
Opened 2021-05-08 20:14 UTC by KaiHerlemann

I solved the OTRS bug [#14522]([url](https://bugs.otrs.org/show_bug.cgi?id=14522)) this way. Because of copyright reasons, I don't copy the text of the OTRS bug.
In short: sending emails signed with S/MIME doesn't work, the email isn't signed. You get an error message in the system log "Can't sign: unable to write 'random state'". This is due to the file permissions, the group has no r/w permissions for the file `$TEMPDIR/.rnd`. If you set them automatically, the system will undo this. Therefore I used a variable so that each user (otrs/apache etc.) has its own .rnd file.
I think it's not working on Windows and maybe *BSD systems. I'm not sure how to solve it there, you have probably more knowledge about that. But locally on CentOS 7 it works.

It's just a workaround, actually I prefer real solutions, but I don't see any way how to solve it.

## Proposed change

## Breaking change

## Additional information

## Checklist

- [x] The code change is tested and works locally.(❗)
- [ ] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

2021-05-19 11:45 UTC, dennykorsukewitz commented
Hi @KaiHerlemann,

this PR is still in 'Draft' mode.
We only look at PRs when they are no longer marked as draft.
Please check.

Thx 🚀

2021-05-20 07:17 UTC, dennykorsukewitz commented
Hi @KaiHerlemann 

```
ZnunyCodePolicy:

[checked] Kernel/System/Crypt/SMIME.pm
TidyAll::Plugin::OTRS::Perl::PerlCritic
Variable, subroutine, and package names have to be in CamelCase: $linux_username at line 2328, column 8. (no explanation).
```

Can you please fix this.
THX 🚀

2021-07-21 18:58 UTC, rkaldung commented
I'm with this solution. The only change I suggest is changing https://github.com/znuny/Znuny/pull/72/files#diff-aafcd3eab2fe2fdba7915b9166fd5ec11b6992b4e3bda4486d34e1c3a0e9463aR2328 to `my $SystemUsername = $<;`

The reason is simple: I'd like to prevent a username lookup on systems with NIS, LDAP, etc.

2021-07-23 12:39 UTC, dennykorsukewitz requested changes

2021-07-23 12:39 UTC, dennykorsukewitz commented on Kernel/System/Crypt/SMIME.pm
> +    my $SystemUsername = getpwuid($<);
```suggestion
    my $SystemUsername = $<;
```

2021-07-25 09:25 UTC, KaiHerlemann commented
works for me.. didn't want to request @dennykorsukewitz for a review, clicked wrong

2021-08-31 11:55 UTC, dennykorsukewitz approved these changes
Looks good to me.
What do you say? @rkaldung

2021-09-25 09:00 UTC, rkaldung approved these changes

2021-10-01 09:55 UTC, merged