Gavatar disabled by default and initials icon prettyfied
znuny/Znuny pull request #82
Opened 2021-05-19 09:26 UTC by pboguslawski

Gavatar should be disabled by default for privacy (user agent activity and
e-mail disclosure) and security reasons (fetching data from external service
is less secure than using only internal resources).

This mod disables Gavatar bu default (still may be enabled in
SysConfig if needed) and prettyfies icon with user initials in
toolbar which is displayed instead of avatar; before

![image](https://user-images.githubusercontent.com/8192649/118789357-fc26bd80-b894-11eb-8ee5-939d37491321.png)

after:

![image](https://user-images.githubusercontent.com/8192649/118789269-e6b19380-b894-11eb-9fce-4655df4f75fa.png)

Author-Change-Id: IB#1108605

2021-05-25 07:53 UTC, rkaldung commented
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

2021-05-28 08:38 UTC, pboguslawski commented
Done.

2022-09-08 15:33 UTC, dennykorsukewitz requested changes
Hi @pboguslawski

please remove the copyrights.
I will apply the other changes as they are. 
With the new design, the CSS part may change again.

🚀

2022-09-08 15:33 UTC, dennykorsukewitz commented on Kernel/Output/HTML/Templates/Standard/Header.tt
> +# Copyright (C) 2021 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
```suggestion
```

2022-09-08 15:33 UTC, dennykorsukewitz commented on var/httpd/htdocs/skins/Agent/default/css/Core.Header.css
> +Copyright (C) 2021 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
```suggestion
```

2022-09-08 15:35 UTC, dennykorsukewitz commented
Hi @pboguslawski,

and please resolve conflicts 👍🏼 

Thanks.

2022-10-14 06:25 UTC, pboguslawski commented
> please remove the copyrights
Done.

2022-10-14 12:04 UTC, dennykorsukewitz commented
> Done.

Thank you 👍🏼 

Could you please check this UnitTest:
That probably needs to be adjusted here...
```
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/Selenium/Agent/AgentPreferences.t:
+-------------------------------------------------------------------+
..................................................................................................................................................................................
 not ok 179 - Avatars disabled message found
..
 not ok 182 - Gravatar message found
....................................................
/opt/otrs/scripts/test/Selenium/Agent/AgentPreferences.t ran 234 test(s) in 48.397s.
```

Regards :rocket:

2022-11-11 11:22 UTC, pboguslawski commented
Unit test fixed in c419370b9b0d9a69b25979ed914de779339aa183.

2023-03-29 08:55 UTC, dennykorsukewitz commented
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

2023-05-17 09:46 UTC, dignin commented
Thanks for your patience. This PR is not acceptable as-is. There are two changes in one. Please separate the changes for the default setting and resubmit if desired. The change to the icon will not be accepted. Pleases modify this in your system if needed.  We also recommend packaging it. 😉

2023-05-17 09:46 UTC, closed without merging