Inline image attachments detection fixes
znuny/Znuny pull request #83
Opened 2021-05-21 21:00 UTC by pboguslawski

Znuny does not recognize inline attachments when formated with
whitespaces like test1.png in sample e-mail added in this commit:

```
 <IMG
             SRC = '
     cid:part1.E5AE6B6E.C188FB97@host1.test'
 alt="" class="">
```

Thunderbird recognizes it and displays as inline image.

When forwarding HTML messages Znuny skips attachments that have
Content-ID somewhere in HTML message body, not in src attribute.
This may cause poorly attached inline images (like test2.png in sample
e-mail added in this commit) to be absent in forwarded message.

This mod fixes above issues, removes redundant replace operations and
fixes inconsistent CID searching regexps.

Related: https://github.com/OTRS/otrs/pull/1256
Author-Change-Id: IB#1052680

2021-05-25 07:51 UTC, rkaldung commented
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

2021-05-28 08:24 UTC, pboguslawski commented
Done.

2021-06-15 12:43 UTC, dennykorsukewitz commented
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

2021-06-15 13:49 UTC, dennykorsukewitz requested changes

2021-06-15 13:49 UTC, dennykorsukewitz commented on scripts/test/PostMaster.t
> +# Copyright (C) 2021 Informatyka Boguslawski sp. z o.o. sp.k., http://www.ib.pl/
```suggestion
```

2021-06-15 13:49 UTC, pboguslawski commented
Done.

2023-03-29 08:55 UTC, dennykorsukewitz commented
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

2023-04-24 12:52 UTC, pboguslawski commented
Replaced by https://github.com/znuny/Znuny/pull/386

2023-04-24 12:52 UTC, closed without merging